### ISSUE TITLE
Not currently installable; ramsey/uuid ~3.0@dev appears to have disappeared

### ISSUE THREAD

**Issue by jimlerza** [r15ch13/peculiar#7]
Switching the ramsey/uuid dependency to "~2.8" should do the trick. At least, that was the solution to [kirkbushell/eloquence issue #7](https://github.com/kirkbushell/eloquence/issues/7).

**Comment by r15ch13** [comment]
Should be fixed now. Please use version 2.0 of Peculiar. :)
